### ISSUE TITLE
more scylla.yaml vars

### ISSUE THREAD

**Issue by tarzanek** [scylladb/scylla-ansible-roles#1]
the whole scylla.yaml can be configured? would it make sense to add other options such as r/w timeouts or warning/fail for batch sizes
I remember cloud folks also add custom fields, so a variable which would just insert what you give it as "key: value" to scylla.yaml would be great
(e.g. enable mc option in 2019.1)
Show less

+ I know cloud folks have such custom settings per some customer clusters and they change them manually, so here we should at least have a notion and know about them

**Comment by dyasny** [comment]
I can make it easy and simply have a `scylla_yaml_parameters` variable as a k:v dictionary, iterate over its keys and push the data into scylla.yaml. Anything smarter would require actual scripting. Do you think this will be enough?

in pseudocode:
```
scylla_yaml_parameters:
  param1: string1
  param2: string2
 etc...


for key in scylla_yaml_parameters:
  apply lineninfile for paramN: stringN to scylla.yaml

```


@tarzanek sounds good enough? This way lineinfile will prevent duplicates in scylla.yaml, and if it actually changed anything, we will have an indication and can trigger restarts or whatever

**Comment by dyasny** [comment]
Oterwise, we can simply edit the scylla.yaml.j2 template adding either a dynamic ansible variable or static cluster-wide settings, the template will get applied and will contain everything in it

**Comment by tarzanek** [comment]
the first idea is ideal 😃
