### ISSUE TITLE
[scylla-ansible-node]: sysctl configuration is not persisted on the disk on a Scylla node

### ISSUE THREAD

**Issue by vladzcloudius** [scylladb/scylla-ansible-roles#109]
*Description*
Today sysctl configuration is only applied by a role but not persisted on a disk, e.g. in /etc/sysctl.conf.

As a result if a VM is rebooted, e.g. due to a cloud vendor maintenance the corresponding configuration is going to be lost.

**Comment by igorribeiroduarte** [comment]
I took a look at one of our prod clusters and the sysctl configuration is already being persisted on `/etc/sysctl.conf`.
