### ISSUE TITLE
When you add your own SSL certificates, nodes playbook ignores them and generates self signed ones

### ISSUE THREAD

**Issue by Rumbles** [scylladb/scylla-ansible-roles#11]
The [documentation](https://github.com/scylladb/scylla-ansible-roles/wiki/ansible-scylla-node:-Deploying-a-Scylla-cluster#ssl-configuration-for-scylla-nodes) states that:

>    To use your own CA, place it in ./ssl/ca/SCYLLA_CLUSTER_NAME-ca.pem and derived per-node certificates will be generated from it, if they are not present.
    To use your own node certificates, create a directory per hostname (same as in the inventory) in ./ssl/HOSTNAME and place the .pem file as HOSTNAME.pem and the .crt file as HOSTNAME.crt

When I tried this, my own certs were ignored and new ones generated. There currently isn't a check to see if certs were provided as the documentation describes (as far as I could see in ssl.yaml)

I have a fix I am currently testing, I will update if I think it is suitable

**Comment by Rumbles** [comment]
I realise now the reason for this is that I only have the CA crt file, but there is no way for me to get a CA pem as that is handled by vault, but I think my changes should be safe for someone who is generating their own CA and for someone who is putting their signed CA pem/crt in the folder

I suppose the wiki needs to be updated to say it also supports you just providing the CA crt and the host crt/pem pairs if you generate them yourself with your own secure CA

**Comment by vladzcloudius** [comment]
@igorribeiroduarte Is it still the case? If "yes", let's fix it.

**Comment by igorribeiroduarte** [comment]
@vladzcloudius Yes, it is. I opened a PR fixing it -> https://github.com/scylladb/scylla-ansible-roles/pull/199
