### ISSUE TITLE
When installing nodes with epel repo, system should reboot before io checks

### ISSUE THREAD

**Issue by Rumbles** [scylladb/scylla-ansible-roles#12]
When installing epel repo, currently the grub doesn't get updated and the machine isn't rebooted before the IO checks, so the kernel is installed, but not used. I feel this could potentially reduce performance test results, so I have a fix which will update grub, reboot the machine then wait until the server becomes available again.

**Comment by dyasny** [comment]
I sent a PR, should be enough to fix this issue

**Comment by Rumbles** [comment]
@dyasny you also need to update grub

**Comment by dyasny** [comment]
@Rumbles that is actually done by the kernel RPM. Easy enough to test manually - just follow the installation steps and reboot, then run `uname -a`

**Comment by Rumbles** [comment]
I did test it, the kernel was not updated when I tested it

> @Rumbles that is actually done by the kernel RPM. Easy enough to test manually - just follow the installation steps and reboot, then run `uname -a`

**Comment by dyasny** [comment]
weird, it worked for me every time... In any case, I added some comments to your PR, I think we both missed a critical step in there.

**Comment by dyasny** [comment]
@Rumbles and of course thank you for stepping in and submitting PRs!
