### ISSUE TITLE
DEB - Installation of specific version doesn't work

### ISSUE THREAD

**Issue by fee-mendes** [scylladb/scylla-ansible-roles#126]
After https://github.com/scylladb/scylla-ansible-roles/commit/8af2a16d746d7e0eee5fa7bf4193c8e0c2bce700 got merged, two situations arose:

1. Trying to install a release that contains both ARM64 and X86 binaries will fail as two lines will be recorded:
```shell
$ apt list -a scylla-enterprise | egrep "2022.1~rc5[\-]?"

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

scylla-enterprise/stable 2022.1~rc5-0.20220515.6a1e89fbb-1 amd64
scylla-enterprise/stable 2022.1~rc5-0.20220515.6a1e89fbb-1 arm64
```

2. Installing a release candidate version fails, because now there is a weird regex check (`regexp: ' ([0-9\.]+)-([a-f0-9\.]+)-([0-9]) '`) which doesn't match a release candidate format: `2022.1~rc5-0.20220515.6a1e89fbb-1`

**Comment by vladzcloudius** [comment]
@tarzanek FYI

**Comment by tarzanek** [comment]
2022 is not yet supported in ansible role
use latest as version to skip this

**Comment by vladzcloudius** [comment]
The first issue is not a Role issue but rather a bug in the `apt` configuration.

The proper `apt` config file should look like this:

```
cat /etc/apt/sources.list.d/scylla-2021.1.list
deb  [arch=amd64] http://downloads.scylladb.com/downloads/scylla-enterprise/deb/debian-ubuntu/scylladb-2021.1 stable main
```

In this case `apt list -a` will only show packages related to the corresponding platform.

So, no need to fix anything in this regard.

As to supporting non-official versions - this feature request can be addressed.

I wonder if that filtering by xx.yy.zz is even required and any random version string as long as it produces a single match is not sufficient?

**Comment by vladzcloudius** [comment]
To address a multi-platform issue EVEN when an apt config file doesn't filter it we can use ` ... | grep $(dpkg --print-architecture)`

**Comment by vladzcloudius** [comment]
On RH it's a non-issue anyway since a platform is encoded in the package name: `scylla-enterprise-2022.1.rc0-0.20220331.f3ee71fba.x86_64.rpm`

**Comment by fee-mendes** [comment]
Additional edge cases introduced:

3. `ansible.builtin.command: /bin/false` throws when Ansible < 2.10, most RHEL and Ubuntu 20.04 installations default to Ansible 2.9. In fact, calling a `builtin.command` just for `/bin/false` doesn't make too much sense as there is a `fail` module exactly for that purpose, which can even print a more meaningful message.

4. Trying to install `2021.1.1` will fail due to the same reasons outlined earlier. With a proper `fail` (instead of built-in) one will see:
```shell
TASK [roles/ansible-scylla-node : Error out, wrong Scylla version was passed(more than a single or none version matches), please fix it!"] ************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": [["2021.1.11", "0.20220516.8e6c9917c", "1"], ["2021.1.10", "0.20220410.e8e681dee", "1"], ["2021.1.1", "0.20210530.ddf65ffc2", "1"]]}
```

Likely one would want something such as `apt list -a {{ scylla_package_prefix }} | egrep "{{ scylla_version }}[^0-9]-?"` . Debatable though...

**Comment by vladzcloudius** [comment]
> ansible.builtin.command: /bin/false throws when Ansible < 2.10, most RHEL and Ubuntu 20.04 installations default to Ansible 2.9. In fact, calling a builtin.command just for /bin/false doesn't make too much sense as there is a fail module exactly for that purpose, which can even print a more meaningful message.

Yes, I noticed that too while working on a fix.


Here is the working version (just a subsection that handles the version fetching and error handling) that addresses all comments above (including arch and RCs) and a few other issues that came unnoticed, e.g. that `grep "2021.1.11" is going interpret `.` and any character and therefore dots have to be escaped.

```
---

- hosts: localhost
  gather_facts: no
  tasks:
  - name: Let's escape {{ scylla_version }}
    set_fact:
      scylla_version_escaped: "{{ scylla_version | regex_escape }}"
 
  - name: Get versions of {{ scylla_package_prefix }} package
    shell: apt list -a {{ scylla_package_prefix }} 2>/dev/null | egrep -v "{{ scylla_version_escaped }}[0123456789]+" | egrep "{{ scylla_version_escaped }}[\-]?" | grep `dpkg --print-architecture` | tr -s ' ' | cut -d" " -f2 | sort | uniq
    register: aptversions

  - name: "Error out, wrong Scylla version was passed(more than a single or none version matches), please fix it!"
    ansible.builtin.fail:
      msg: "Too many/few choices: {{ aptversions.stdout_lines }}. Bailing out!"
    when: aptversions.stdout_lines | length != 1
 
  - debug:
      msg: "{{ aptversions}}"

  - name: Search for version of {{ scylla_package_prefix }} package
    set_fact:
      tempsversion: "{{ aptversions.stdout | regex_findall(regexp, ignorecase=True) }}"
    vars:
      regexp: '^([a-z0-9\.\~]+)-([a-f0-9\.]+)-([0-9])$'

  - debug:
      msg: "{{ tempsversion }} {{ tempsversion | length }}"

  - name: Set {{ scylla_package_prefix }} version if only one version found
    set_fact:
      sversion: "{{ tempsversion }}"
 
  - debug:
      msg: "{{ tempsversion }} {{ tempsversion | length }}"

```
[test.zip](https://github.com/scylladb/scylla-ansible-roles/files/8983875/test.zip)
[results.zip](https://github.com/scylladb/scylla-ansible-roles/files/8983876/results.zip)

Above is the same playbook and results of following executions on a U20 VM with 2021.1.11 installed:

```
$ ansible-playbook  ./test.yml --extra-vars '{"scylla_package_prefix":"scylla-enterprise", "scylla_version":"2021.1~rc2"}' >> ./results.txt
$ ansible-playbook  ./test.yml --extra-vars '{"scylla_package_prefix":"scylla-enterprise", "scylla_version":"2021.1.1"}' >> ./results.txt
$ ansible-playbook  ./test.yml --extra-vars '{"scylla_package_prefix":"scylla-enterprise", "scylla_version":"2021.1.11"}' >> ./results.txt
```

I'm going to test this in a full Role tomorrow.

**Comment by vladzcloudius** [comment]
The above testing has been done in a presence of apt config as it would come for 2022.1 (the same way  @fee-mendes had it when it failed for him), meaning with arm64 packages "visible".

I wasn't able to test *exactly* the same setup because I didn't have a 2022.1 repo pgp code. 

@fee-mendes When/if you have time, please, test that small playbook above against 2022.1 and tell if it works as expected.

Here are tests releases strings that I usually check:
* Good cases: 
  * RC name.
  * A release string that could translate to multiple releases but shouldn't : e.g. `2021.1.1`.
  * A full release string, e.g. `2021.1.1-0.20210530.ddf65ffc2-1` or `2021.1.1-0.20210530.ddf65ffc2`
* Bad cases: 
  * A release string that DOES translates to multiple versions: `2021.1`
  * Non existing valid release string: 2021.1.30 or `2021.1.41-0.20210530.ddf65ffc2-1`

**Comment by vladzcloudius** [comment]
> 

Thanks a lot for confirming, @hopugop.

Here is the current (pre-full-system-tests) version of the playbook above (there are a few changes that address issues hard to hit using current 2021.1 and 2022.1 repos) but that must have been addressed (run a `diff` to see those changes).

[test.zip](https://github.com/scylladb/scylla-ansible-roles/files/8996495/test.zip)

Please, take a look and give a feedback if needed.
I'm moving to full system tests in the meantime.

Test cases I'm going to run:

1) Installing specific version - latest (specified explicitly).
2) Installing specific version - not the latest.
3) Downgrade to a minor version lower than installed.
4) Upgrade to a specific version - latest (explicitly specified).
5) Upgrade to a specific version - not latest.

**Comment by hopugop** [comment]
@vladzcloudius I repeated my tests with that latest version you provided and it looks good.
Also good comments on explaining the logic, regexes can be hard to grasp after not touching the code for a while.
LMK when you have it committed so I can test actually installing 2022 RCs.

**Comment by vladzcloudius** [comment]
Branch `scylla-node-role-fix-debian-installation` in 
 https://github.com/vladzcloudius/scylla-ansible-roles.git

You can give it a try (don't give to a customer yet!), @hopugop
