### ISSUE TITLE
[ansible-scylla-node]: io_properties.yml is empty with 2022.1.x

### ISSUE THREAD

**Issue by vladzcloudius** [scylladb/scylla-ansible-roles#196]
HEAD: dd134fd59237aee86c71c0412b5a78aa01349b73

*Description*
When a Node Role runs 2022.1.x `iotune` io_properties.yml comes out empty.

**Comment by vladzcloudius** [comment]
@igorribeiroduarte Please, reference a path that fixed this and close.

**Comment by igorribeiroduarte** [comment]
Fixed in https://github.com/scylladb/field-engineering/pull/1277
