### ISSUE TITLE
elrepo kernel should be set as default (if elrepo + centos 7 used)

### ISSUE THREAD

**Issue by tarzanek** [scylladb/scylla-ansible-roles#21]
if centos 7 is used, elrepo kernel needs to be explicitely enabled by:
```
sudo grub2-set-default 0
```

**Comment by dyasny** [comment]
This should be fixed by PR #13

**Comment by tarzanek** [comment]
merged the PR, will retest with Centos 8

**Comment by tarzanek** [comment]
closing, works with the PR even on Centos 8
