### ISSUE TITLE
rolling restart example doesn't wait for "serving" status

### ISSUE THREAD

**Issue by tarzanek** [scylladb/scylla-ansible-roles#26]
nor does it wait for cqlsh port
so this rolling restart isn't that friendly to cql clients

- above is for seed hosts - resp when switching from seeds to non-seeds

**Comment by tarzanek** [comment]
https://github.com/scylladb/scylla-ansible-roles/blob/master/example-playbooks/rolling_ops/rolling_restart.yml#L71
checks for nodetool status to become UN
which however isn't the state of "serving"

**Comment by dyasny** [comment]
What __is__ the state of "serving? Check for open port 9042?

**Comment by r4fek** [comment]
`nodetool statusbinary` tells that.
