### ISSUE TITLE
support for 5.4 and 2024

### ISSUE THREAD

**Issue by tarzanek** [scylladb/scylla-ansible-roles#338]
@nopzdk tested 2024 with role and figured we miss few values by default (below were taken from default 2024 scylla.yaml) in 
https://github.com/scylladb/scylla-ansible-roles/blob/master/ansible-scylla-node/templates/scylla.yaml.j2

```
schema_commitlog_segment_size_in_mb: 128
task_ttl_in_seconds: 10
strict_is_not_null_in_views: true
force_schema_commit_log: true
consistent_cluster_management: true
```

we could optionally add another good default:
```
native_shard_aware_transport_port: 19042
```

without it the shard aware port is not properly serving (it forwards to 9042 without above)

**Comment by tarzanek** [comment]
and ev.
```
enable_shard_aware_drivers: true
```
(the last two should be on by default, but our c-s tests didn't confirm that, so let's validate and file bug against Scylla if we can repro)

**Comment by vladzcloudius** [comment]
It's not Role's job to override a SW package defaults by default in general.

Scylla Node Role provides all necessary tooling for that however.
If you believe that Scylla/Scylla Enterprise defaults are wrong you should report it on the the corresponding Scylla/Scylla Enterprise project - not here.

**Comment by tarzanek** [comment]
It's more about updating OUR template to USE defaults

e.g. 
enable_shard_aware_drivers: true
native_shard_aware_transport_port: 19042

are like that in default config.cc but it seems Scylla won't cut it without above in scylla.yaml (there is a bug in scylla core about it @nopzdk what is the number?)
