### ISSUE TITLE
scylla-monitoring: GCP Snitch suffix (resp. any suffix) doesn't get used for the monitoring label

### ISSUE THREAD

**Issue by tarzanek** [scylladb/scylla-ansible-roles#353]
e.g. I have in inventory
```
mylittlenode dc=asia-south2 dc_suffix=-mysuffix zone=asia-south2-a rack=a
```

I use GCP snitch

then the DC label in monitoring should be 
asia-south2-mysuffix
BUT 
it is only asia-south2

@igorribeiroduarte I think this is a regression when we stopped using nodetool status as for input for monitoring config generation
and started using inventory
@vladzcloudius fyi

**Comment by vladzcloudius** [comment]
@igorribeiroduarte, please, send a patch. Should be a trivial one.
