### ISSUE TITLE
[Replace node]: checks a joined node health from other nodes perspective serially

### ISSUE THREAD

**Issue by vladzcloudius** [scylladb/scylla-ansible-roles#371]
HEAD: 96c877668c1c57d1bf97fb983e68d63e0354efb3

## Description
The task that tests that the node has become `UN` from all other nodes' perspective does it serially which is pretty terrible of large enough clusters: https://github.com/scylladb/scylla-ansible-roles/blob/master/example-playbooks/replace_node/replace_node.yml#L195

**Comment by igorribeiroduarte** [comment]
Fixed by https://github.com/scylladb/scylla-ansible-roles/pull/373
