### ISSUE TITLE
Missing pipe results in malformed io_properties.yaml file

### ISSUE THREAD

**Issue by pdbossman** [scylladb/scylla-ansible-roles#374]
pipe is missing from io_properties in  `ansible-scylla-node/defaults/main.yml`.

Fails subtly by producing badly formatted `/etc/scylla.d/io_properties.yaml `file.

```
# These can be arbitrarily set if scylla_io_probe is set to False
# io_properties: 
#   disks:
#     - mountpoint: /var/lib/scylla/data
#       read_iops: 10962999
#       read_bandwidth: 348093056
#       write_iops: 9722999
#       write_bandwidth: 352182944
```

Additionally, if `io_properties.yaml `is malformed, the file needs to be deleted before rerunning.  If it's not deleted, the step will be skipped and malformed file remains.

**Comment by igorribeiroduarte** [comment]
Thanks for this issue, @pdbossman.
I'll send a PR adjusting the defaults.

Regarding your comment about the role not replacing `io_properties.yaml`, this is done on purpose.
We want to avoid replacing any already existing io_props (that may have been manually tuned by the user) unless we're explicitly told to. There is a flag named `always_replace_io_properties` which when set to true will `tell` the role to replace the existing io_properties file.
