### ISSUE TITLE
replace_node.yml: there is a conflict on a `install_type` field in Node, Monitor and Manager Roles

### ISSUE THREAD

**Issue by vladzcloudius** [scylladb/scylla-ansible-roles#385]
HEAD: 40194e595cda5a4baf71ac4309cb696a5cef1902

## Description
Since `replace_node.yml` invokes multiple Roles and therefore needs to receive configurations of all of them there must be no collision between parameters with the same name.
In general there should be no parameters with the same name.

However, unfortunately, there are.
One of them is `install_type`.

As a result, if a Node Role has it explicitly set in the config file passed to `replace_node.yml` and has a value `online` this is going to make a Monitor Role to install a non-docker installation while in fact this was unintended (default is a docker installation).

We should rename all such parameters to have a unique name, e.g.:
* scylla_install_type
* monitor_install_type
* manager_install_type

**Comment by igorribeiroduarte** [comment]
Fixed by https://github.com/scylladb/scylla-ansible-roles/pull/389
Closing this issue
