### ISSUE TITLE
Do not use hardcoded group name

### ISSUE THREAD

**Issue by elcomtik** [scylladb/scylla-ansible-roles#45]
I found that using my own group name for cluster nodes is impossible due to its hardcoded values in the role.
https://github.com/scylladb/scylla-ansible-roles/blob/master/ansible-scylla-node/defaults/main.yml#L93
https://github.com/scylladb/scylla-ansible-roles/blob/master/ansible-scylla-node/templates/cqlshrc.j2#L6-L14

I would solve it by introducing a variable containing the name of group that is used.

**Comment by dyasny** [comment]
Since these are used for Scylla deployments, I don't really see anything too bad about hardcoded groups, and having them makes life a little bit easier in the code. Hardcoded groups are pretty much standard practice everywhere else (kubespray, OSP installer, infrared, linchpin etc)

**Comment by elcomtik** [comment]
This prohibits creating more than one cluster per one inventory. This group_name variable can default to some specific value, eg. scylla, which is currently used.

**Comment by dyasny** [comment]
This does make sense, though nothing really prevents you from keeping multiple inventories

**Comment by elcomtik** [comment]
> though nothing really prevents you from keeping multiple inventories

I agree, I may do that.
