### ISSUE TITLE
Artifacts generated by roles should be stored outside of playbook hierarchy

### ISSUE THREAD

**Issue by elcomtik** [scylladb/scylla-ansible-roles#47]
I used the role ansible-scylla-node for the setup of my cluster and find it quite annoying that it produced artifacts, which were placed into the playbook directory.

The artifacts in concern:
```
        plays/scylla/scylla_deploy/cqlshrc
        plays/scylla/scylla_deploy/monitoring.yml
        plays/scylla/scylla_deploy/scylla_servers.yml
        plays/scylla/scylla_deploy/scyllamgr_auth_token.txt
        plays/scylla/scylla_deploy/ssl/
```

I suppose users place their playbook into the git repository usually, so these files need to be ignored at least. Another problem arises when the user wants to deploy multiple clusters by the same playbook. The artifacts will be replaced, which may not be intended. 

I think it would be much better if it would be placed into the user's home dir in a folder e.g. ~/.scylla or ~/.ansible_scylla.

The last observation related to these artifacts. It would be great if they can be loaded from vars. This would allow storing them encrypted by ansible-vault or Hashicorp vault and sharing them between team members collaborating on the same project. If the user would like to use the same files as currently generated, it would be possible by loading them with an appropriate ansible lookup plugin to the corresponding variable. Default values for these variables may reference unencrypted artifacts.

**Comment by dyasny** [comment]
Thanks, I've been thinking along the same lines myself, but this initial release was more along the flow that would match a simpler flow:
Create a cluster dir, update the vars for the cluster, check out the roles and whatever else, keep running the plybooks that apply the roles. Keep the entire thing under version control to keep track of changes. 

PRs are welcome of course, keeping the keys and other data encrypted was on the radar so it will make sense to make things more vault-friendly

**Comment by elcomtik** [comment]
I understand that these roles are fairly new. I just deployed my first Scylla cluster for evaluation purposes and pointed out a few issues/improvements, which popped out to my mind. If Scylla will be adopted, then I may create PR for these improvements.

**Comment by elcomtik** [comment]
There is much more to be improved, however, my time allocations cannot cover all of it.

**Comment by dyasny** [comment]
Sounds good, I hope to see Scylla adopted and your continued use of these roles as well as community participation :) 

The roles were released as soon as they were functional enough for actual work, but of course there's a lot of work left to make them even better
