### ISSUE TITLE
Package list not updated

### ISSUE THREAD

**Issue by pveentjer** [scylladb/scylla-ansible-roles#67]
I have created 2 Ubuntu 20.04 instances on EC2 and when I install Scylla using the Ansible roles, it runs into various problems because no 'sudo apt-get update' was executed. And some packages like Scylla and gnugp2 are not found.  So I need to manually log into the nodes, execute the update, then then the installation will continue.

So before any software is installed, the package list should be updated.

**Comment by elcomtik** [comment]
duplicate of https://github.com/scylladb/scylla-ansible-roles/issues/44

**Comment by pveentjer** [comment]
Thanks! :)
