### ISSUE TITLE
aws i3 support

### ISSUE THREAD

**Issue by sanmoengage** [scylladb/scylla-ansible-roles#75]
Since the aws i3 instances have the optimized ami already, do these ansible roles support the deployment and rolling restart on i3 instances?

With the aws i3 ami, we are seeing issues when we stop and start the node due to "Failed to mount RAID volume". Does this ansible script support a fix for this?

**Comment by dyasny** [comment]
The rolling restart playbook restarts nodes, it doesn't stop/start them. That means the ephemeral disks are not lost if cloud instances are managed.

**Comment by sanmoengage** [comment]
Got it. 

I needed help on how to deploy scylla using these ansible roles on a fresh i3 instance. I have following questions on my mind.

1. Assume that I have spawned a set of three new i3 instance with the Scylla AMI, can I use these ansible roles and deploy scylla and form a cluster? 

2. AFAIK, the scylla servers would have started when these i3 instances come up with Scylla AMI. So in that case will the deployment using these roles work and form the cluster?

3. If I bring up a new i3 instance with scylla AMI, can I use the add_node ansible role to join this node to the existing cluster?

**Comment by dyasny** [comment]
If you installed from the AMIs, you don't need these roles to deploy Scylla, you already have it deployed. 

Also, this is not really an issue, and it would be better to go to the Scylla slack channels or the mailing list.

**Comment by sanmoengage** [comment]
Sure thanks.
