### ISSUE TITLE
add support for cql monitoring when there is auth

### ISSUE THREAD

**Issue by tarzanek** [scylladb/scylla-ansible-roles#78]
to support showing large*
you need to do:

https://github.com/scylladb/scylla-monitoring/tree/branch-3.7/grafana/plugins/scylla-plugin

so if we know a password we can prepare above session and add it when deploying monitoring

**Comment by vladzcloudius** [comment]
@tarzanek What's the status of this?

**Comment by vladzcloudius** [comment]
Dup of https://github.com/scylladb/scylla-ansible-roles/issues/93
