### ISSUE TITLE
cassandra-stress role

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla-ansible-roles#8]
When demo Scylla, its useful to have a "loader" role running cassandra-stress.
For such a role, one need to set:
- number and type of nodes
- parameters for c-s
- List of Scylla node IPs to send traffic to

See similar function here https://github.com/scylladb/ansible-cassandra-cluster-stress-historical#launch-loaders

**Comment by dyasny** [comment]
Thanks for the RFE, this is already ion the roadmap, and a major part of the code is already complete

**Comment by dyasny** [comment]
Fixed in https://github.com/scylladb/scylla-ansible-roles/commit/ea81877f49c979ab988af3a41c06d8f4bb3c1f5f
