### ISSUE TITLE
remove "latest" from monitoring

### ISSUE THREAD

**Issue by tarzanek** [scylladb/scylla-ansible-roles#81]
as per https://github.com/scylladb/scylla-monitoring/issues/1547
we should drop using latest in versions of monitoring:

https://github.com/scylladb/scylla-ansible-roles/blob/master/ansible-scylla-monitoring/defaults/main.yml#L27

**Comment by vladzcloudius** [comment]
@tarzanek is this still relevant?

**Comment by tarzanek** [comment]
fixed in https://github.com/scylladb/scylla-ansible-roles/commit/d86afe2a1cfe08d8c1033bdcad0611cb6c32334b
