### ISSUE TITLE
add explicit support for encryption at rest

### ISSUE THREAD

**Issue by tarzanek** [scylladb/scylla-ansible-roles#84]
Add explicit support as per https://docs.scylladb.com/operating-scylla/security/encryption-at-rest/#set-the-kmip-host
now it's only available using https://github.com/scylladb/scylla-ansible-roles/wiki/ansible-scylla-node:-Deploying-a-Scylla-cluster#all-other-scyllayaml-parameters

**Comment by tarzanek** [comment]
dup of https://github.com/scylladb/scylla-ansible-roles/issues/88 ?

**Comment by vladzcloudius** [comment]
Closing as a duplicate.
