### ISSUE TITLE
cleanup should skip non existent tables

### ISSUE THREAD

**Issue by tarzanek** [scylladb/scylla-ansible-roles#87]
```
00:01:41.070         "cleanup of stressexample rawtest",
00:01:41.070         "Using /etc/scylla/scylla.yaml as the config file",
00:01:41.070         "nodetool: Keyspace [stressexample] does not exist.",
00:01:41.070         "See 'nodetool help' or 'nodetool help <command>'."
00:01:41.070     ],
00:01:41.070     "warning": "The job has failed and was not cleaned up properly. Please, delete job alias manually to restart."
```

the cleanup.sh script can find empty directories of removed keyspaces/tables and it should skip them and not fail completely

**Comment by vladzcloudius** [comment]
`cleanup` script should not be looking at directories to begin with.
It should look at the current schema.

**Comment by tarzanek** [comment]
cleanup should also properly skip with RC=0 in case there are no user keyspaces

**Comment by tarzanek** [comment]
use REST to get live list of KS and tables?

**Comment by tarzanek** [comment]
curl -XGET "http://localhost:10000/storage_service/keyspaces" 

above is json and needs filtering out of scylla ones
["audit","system_auth","notification_service","system_schema","system_traces","system_distributed","system"]

however it seems we lack any column family/table query API

**Comment by tarzanek** [comment]
so another idea is to check if directory contains sstables and only use it if it has any (yes, non flushed tables wouldn't be considered, but then do we care? flush will only flush its owning tokens I'd hope)
