### ISSUE TITLE
support encryption at rest explicitely (not only using scylla_yaml_params)

### ISSUE THREAD

**Issue by tarzanek** [scylladb/scylla-ansible-roles#88]
so https://docs.scylladb.com/operating-scylla/security/encryption-at-rest/ is not part of the role as per se, but you can dynamically add a directory with keys for system_key_directory or for system_info_encryption from https://docs.scylladb.com/operating-scylla/security/encryption-at-rest/#encrypt-system-resources by using extra scylla_yaml_params
https://github.com/scylladb/scylla-ansible-roles/blob/master/ansible-scylla-node/defaults/main.yml#L187
of course generating the key and setting it up for user tables is not part of role
so you need to manually create them as per
https://docs.scylladb.com/operating-scylla/security/encryption-at-rest/#create-encryption-keys

we should add support for system tables, since they change scylla.yaml, user tables can still be outside of the role (cql access, but expects keys on all nodes)

**Comment by vladzcloudius** [comment]
@tarzanek I'm not sure I understand what needs to be done or is missing.
What does "add support for system tables, since they change scylla.yaml" means exactly?

**Comment by tarzanek** [comment]
this is mainly about more parameters (keys) that need to be passed to role to fully support encryption at rest
we had few questions to get this supported officially, current support is clumsy or not fully working
so basically it's about above use case per docs and testing it (ev. adding what is needed to params) so it is streamlined and working

**Comment by igorribeiroduarte** [comment]
Fixed by https://github.com/scylladb/scylla-ansible-roles/pull/282
