### ISSUE TITLE
Authenthication enabling should adjust replication of system_auth keyspace

### ISSUE THREAD

**Issue by tarzanek** [scylladb/scylla-ansible-roles#9]
default system_auth is set to RF=2  with simple strategy
for a cluster this should be set to NetworkTopology + RF = number of nodes and trigger a repair
otherwise every auth connect triggers connections around the cluster and not local ones

**Comment by dyasny** [comment]
This is true, but schema changes require CQL access, and that would mean the playbooks will have to be fed credentials. I think it would make much more sense to move all CQL related automation to a separate project (a pile of scripts really) that uses a Scylla driver and does the right things there. Those can be triggered by the roles in turn of course.

**Comment by mykaul** [comment]
@vladzcloudius - thoughts?

**Comment by vladzcloudius** [comment]
We can implement it for now.
