### ISSUE TITLE
drop the dependency on swap, scylla setup in 2021 does it by itself

### ISSUE THREAD

**Issue by tarzanek** [scylladb/scylla-ansible-roles#90]
remove `swap_file_size_mb`
variable and dependency
for 2021 scylla version

**Comment by vladzcloudius** [comment]
@igorribeiroduarte Please, check if we still need to use the geerlingguy.swap with the supported releases (2021 and up).

**Comment by igorribeiroduarte** [comment]
PR removing this dependency -> https://github.com/scylladb/scylla-ansible-roles/pull/201
