### ISSUE TITLE
scylla node role: /etc/scylla.d/memory.conf seems not to be generated

### ISSUE THREAD

**Issue by ebenzecri** [scylladb/scylla-ansible-roles#98]
It seems `/etc/scylla.d/memory.conf` is not being automatically generated when the role is used

**Comment by vladzcloudius** [comment]
@ebenzecri Please, make sure that all FC clusters are using this.

**Comment by vladzcloudius** [comment]
@tarzanek Is it fixed already?

**Comment by tarzanek** [comment]
so we need to add support for this (and for any new options for scylla_setup in 2021/2022)
with default to lock it by default - https://github.com/scylladb/scylladb/blob/master/dist/common/scripts/scylla_setup#L269
so in a sense there is nothing really to do here, unless we want to give people options not to do this (which is a corner case)

I will prepare a PR

**Comment by vladzcloudius** [comment]
@tarzanek was there any progress on this?
